// Thao Ha IN200 C++
// Mid-term Exam - Code Creation
//

#include <iostream>
#include <stdlib.h>
#include <string>
#include <vector>

using namespace std;

vector<string> locations;
vector<string>::iterator iterOutput;

void AddLocation(string aLocation) {
    locations.push_back(aLocation);
}

int CreateNum() {
    int rNum = (rand() % 5);
    return rNum;
}

int main() {
    string myName = "Thao Ha";
    string input;
    double arr[5] = {3.1415, 7.777, 55, 9999.99, 1};
    int i;
    int intNum;
    int arr100[100];

    cout << "The size of my name (" << myName << ") is " << myName.size() << ".\n";

    cout << "The array contains 5 floating point numbers:\n";
    for (i=0; i<5; i++) {
        cout << i+1 << ") " << arr[i] << "\n";
    }

    cout << "Please enter an integer number in the range between 1 and 100: ";
    cin >> intNum;

    if (intNum > 100) {
        cout << "You have entered the number greater than 100. Please try again with other number: ";
        cin >> intNum;
    }
    else if (intNum > 66) 
        cout << "Your number is in the top 1/3 of possible numbers.\n";
    else if (intNum == 33) 
        cout << "Your number is exactly the number I was looking for!\n";
    else 
        cout << "Your number is unremarkable.\n";
    
    do {
        cout << "Please enter a location or type \'quit\': ";
        cin >> input;
        AddLocation(input);      
    }  
    while(input.compare("quit"));

    for(iterOutput = locations.begin(); iterOutput != locations.end(); iterOutput++){
        cout << *iterOutput << ' ';
    }

    cout << "\nWe have 100 random number generated by the system:\n";
    for (i=0; i<100; i++) {
        arr100[i] = (rand() % 1000) + 1;
        cout << i+1 << ") " << arr100[i] << "\n";
        if (arr100[i] == 666) {
            cout << "Creating salt circle\n";
            break;
        }      
    }
 
    switch(CreateNum()) {
        case 0: 
            cout << "The random number is equal to 0.\n"; 
            break;
        case 1:
            cout << "The random number is equal to 1.\n"; 
            break;
        case 2:
            cout << "The random number is equal to 2.\n"; 
            break;
        case 3:
            cout << "The random number is equal to 3.\n"; 
            break;
        case 4:
            cout << "The random number is equal to 4.\n"; 
            break;
    }

    return 0;
}